### PR TITLE
Change the order in finish-args

### LINKED ISSUE #4: Files are sometimes downloaded inside a sandbox
This is the third time Fragments downloads a file in a temporal sandboxed directory instead of `~/Downloads`. For some reason, inside the sandbox, `ls ~` only shows `Dropbox src` where `src` is a personal folder in my home. It doesn't show any other file. Adding `--filesystem=~/Downloads` fixes the issue, but I am not sure why this app uses `--filesystem=home` and it is not being taked into account.

### PR DESCRIPTION
**Pull request by A6GibKm**
Fixes #4 for me. Also two minor changes to the manifest.

### CODE REVIEW

**Comment by alatiera** [comment]
Why the preferences for archives over git trees? It only makes things harder to maintain.

**Comment by A6GibKm** [comment]
Downloads less data, and can be cached by `flatpak-builder`. Aditionally, tags can be modified upstreams while archives  with an specific sha256sum can't.

**Comment by alatiera** [comment]
> Downloads less data, and can be cached by `flatpak-builder`. 

flatpak-builder is caching git repositories as well

> Aditionally, tags can be modified upstreams while archives  with an specific sha256sum can't.

Yes, if you are worried about tags, you can specify the exact git object you want.

**Comment by A6GibKm** [comment]
If it is a blocker I can either remove that commit, or specify a commit on top of the tag on the sources, just say it so.

**Comment by A6GibKm** [comment]
This became irrelevant due to 438c3e948fcd8ee43a96faf7561eb902fec7de47.

**Pull request closed without merging**
